### ISSUE TITLE
Best license

### ISSUE THREAD

**Issue by CapnKernel** [McNugget6750/pypilot-motor-electronics#2]
Hi,

Some people (including me) are of the opinion that GPL 3 doesn't really map well to hardware designs.  Example discussion:

  https://reprap.org/forum/read.php?33,40874

Three common licenses for open source hardware are CC (I suggest CC-BY-SA 4), CERN OHL and TAPR:

https://www.oshwa.org/faq/
https://opensource.com/law/15/2/intro-open-hardware-licensing
https://www.oshwa.org/open-source-quick-reference-guide/
https://www.oshwa.org/wp-content/uploads/2014/08/Open-Source-Hardware-Checklist-1.pdf

Would also be good to have an OSHW logo on your board, and your name and a copyright :-)

**Comment by McNugget6750** [comment]
Honestly, I'm totally open. I added GPL because I needed to add "some" license at least.
I'll change the license to a CC license.

**Comment by McNugget6750** [comment]
Done.
